### ISSUE TITLE
Read GDB Error Unable to open "4c4fb1c7c5117859fb776e5e4b659Database.gdb" for mode "ReadAllowWrite" 

### ISSUE THREAD

**Issue by RichardScottOZ** [GeosoftInc/gxpy#141]
This was working fine this morning (and all week, many times)

Just stopped - can open the file fine in Oasis Montaj viewer, the file exists etc.  I did reinstall the package (and the viewer).  Any idea what else could be wrong?

Some sort of Seequent account corruption?

```python

Unable to open "4c4fb1c7c5117859fb776e5e4b659Database.gdb" for mode "ReadAllowWrite" because (The system cannot find the file specified.
). Directory or file not found, unreadable or may already be open.
Traceback (most recent call last):
  File "C:\Users\rscott\gdb_read.py", line 50, in convert_gdb
    gdb = gxdb.Geosoft_gdb.open(file_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\gdb2\Lib\site-packages\geosoft\gxpy\gdb.py", line 404, in open
    gdb._db = gxapi.GXDB.open(_gdb_name(name), 'SUPER', '')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rscott\AppData\Local\miniconda3\envs\gdb2\Lib\site-packages\geosoft\gxapi\GXDB.py", line 1772, in open
    ret_val = gxapi_cy.WrapDB._open(GXContext._get_tls_geo(), file.encode(), user.encode(), password.encode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gxapi_cy.pyx", line 12012, in gxapi_cy.WrapDB._open
  File "gxapi_cy.pyx", line 8382, in gxapi_cy._raise_on_gx_errors

```

**Comment by serban-seeq** [comment]
Looks like its locked by another process. maybe another instance of gx developer or a zombie process. Does it resolve after a reboot?

If still reproducible with a specific gdb pls attach to the issue otherwise we wont be able to investigate.

**Comment by RichardScottOZ** [comment]
Yes... I think it was some sort of transient network issue perhaps that caused an issue. Thanks for the info...will know in future.
